services:
  
  web:
    build: ./projedata/Dockerfile
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_events
      MYSQL_USER: root
      MYSQL_PASSWORD: "#20022005Re"
    ports:
      - 3366:3306
    
  