spring.application.name=projedata
spring.datasource.url=jdbc:mysql://localhost:3306/db_events
spring.datasource.username=root
spring.datasource.password=#20022005Re
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# driver do banco de dados MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver